### ISSUE TITLE
words.csv?

### ISSUE THREAD

**Issue by gitonthescene** [ohare93/brain-brew-starter#1]
I think there is a typo in the README.  There is a mention of the “csv words.json”.

**Comment by jeprecated** [comment]
> I think there is a typo in the README. There is a mention of the “csv words.json”.

That is indeed a typo! :sweat_smile: Thanks for pointing it out :+1: 

Thank you for taking a look at Brain Brew :+1: I hope it is of some use to you, and I am open to answer any questions if I can with that :smile: 
 
Fyi: this Brain Brew Starter project is running Brain Brew 0.1.5, whereas I have updated Brain Brew to 0.3.1 over the last year. Therefore lots of the things in here are rather old compared to the newly improved versions (that were made in conjunction with the upgrade of the [Ultimate Geography repo](https://github.com/axelboc/anki-ultimate-geography)). Suffice to say this helper project to get people started needs some love! :sweat_smile: I hope to do that this coming week. In the meantime Ultimate Geography is the best running example of Brain Brew out there :+1:

**Comment by gitonthescene** [comment]
Okay.  I'm happy to offer feedback as to what's confusing for an absolute noob if you'd like.  I can either get started now or wait until you've made your changes if you prefer.

**Comment by jeprecated** [comment]
@gitonthescene I have now updated this Brain Brew starter project to the latest version of Brain Brew :+1: Please play around with it, and let me know if there's anything that can be clearer! (There is, of course! :sweat_smile:)

As I say in the ReadMe, I am working on an easier method of getting a user setup with their own working recipe. Should be out in a few weeks at worst :+1:

**Comment by jeprecated** [comment]
@gitonthescene New functionality has been release in Brain Brew to autogenerate the files needed for a Brain Brew repo using your own flashcards :+1: if you are still interested in trying it out, it is now easier than ever :+1:  https://github.com/ohare93/brain-brew/releases/tag/v0.3.4

**Comment by gitonthescene** [comment]
Thanks very much!  I am interested.  I just need to carve out some time.

**Comment by gitonthescene** [comment]
Sorry.  It took so long, but I finally tried it.  It works great!  I plan on exercising it some more.  I'll let you know if issues crop up.  Thanks again!
