### ISSUE TITLE
Maybe be explicit about what's needed to start new projects?

### ISSUE THREAD

**Issue by gitonthescene** [ohare93/brain-brew-starter#4]
Hey there,

It's not a complaint at all.  In fact I'm not sure it's even a very good suggestion, but I thought I'd offer it as food for thought.  When making your own projects in GitHub based on this project, you probably don't want to fork this project, since if you forked and tried to sync up later, you'd probably have issues with the `src` and `recipes` folders.  Really all you need are the `Pipfile` and the `Pipfile.lock` files.  Might it be worth making that explicit in the `README`?

In any event, this project is working splendidly for me so far.  Thanks very much.

Regards

**Comment by jeprecated** [comment]
This project started off as a clonable repo, which became less useful when I implemented the Init function. Though I do say in the ReadMe that one should delete those folders https://github.com/ohare93/brain-brew-starter#setting-up-your-own-cards-for-importexport I could probably be more explicit at the top about it :sweat_smile: Thanks for the feedback, I will make a change soon. Glad it's all working well for you still :+1:
