### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'description'

### ISSUE THREAD

**Issue by orgtre** [ohare93/brain-brew-starter#6]
Hi, interesting project, I'm just trying it out, but got the error from the title when running `brainbrew init [path-to-crowdanki-export]`. 

For some reason I get `"description": "` entries in all the `flds` of one of my `note_models` in the crowdanki json. Once I delete them manually the error disappears and the command runs without errors.

Also, after the init command runs I get the message "You should now run `brainbrew run recipes/source_to_anki`", but when I try that it gives a FileNotFoundError as one really needs to run `brainbrew run recipes/source_to_anki.yaml`.

**Comment by orgtre** [comment]
After changing the Pipfile to require Brain Brew v0.3.8 (and regenerating the lockfile) the error changes into 
```
WARNING:root:Unexpected values found when creating 'CrowdAnki': ['description']
!!! Please report this error if it seems strange
```
So to avoid the error it is enough to update the Brain Brew version in this repo.

**Comment by jeprecated** [comment]
Hello! Thanks for trying it out, and sorry for the issues.

I don't see an obvious reason why Description is showing up like that. But at least it is fixed in latest! 😅 I see I let the version get a little stale in this repo, so I'll get that fixed 👍

**Comment by jeprecated** [comment]
Fixed :+1: thanks again for the report. Feel free to ask any questions here or in Discussions :+1:
